#!/bin/bash
echo "                              .ZMMMMMN.     ..:+=. "
echo "        ,NMNZ~..             .MMZZZZZMM,.ZMMMMMMMM?."
echo "      .+MM+=ZMMMMN......,++I7MMZZZZZZZMMMM~......+M~ "
echo "      ~M8.......~MMMMMMMMMMMMMZZZZZZZZZM8.........MM"
echo "      MM...................~MZZZZZMMMMZMM8,.......MM."
echo "     .MM...................NMZZZZZMZZMM8ZZMMMNMMMMMM."
echo "     .MN...................M8ZZZZZMMMMZZZZZZMMZZZZZMM,"
echo "     .MM...................IMZZZZZZZMZZZZZZZMMZZZZZZMM"
echo "      MMMM..................NMM8Z8MMM8ZZZZZZMMMMZZZZMM.."
echo "      ,MM.....................+ZZ?,.?M8ZZZ8MMZMMZZZZMZ,,"
echo "     .MM..............................+MMMMZZ8ZZZZZMN.MMZ+~,"
echo "     +M7.................................~MZZZZZZMMMM.MMMMMM8I~,"
echo "    .MN...................................:MMMMMMN.,MIMMMMMMMMMN"
echo "    ?M~.............................................MMMMMMMMMMMM"
echo "    NM..............................................MM.?ZMMMMMMM"
echo "    MM...........................................~NMMMMMMMMN8MMM"
echo "..:+IMMZI:........................................?I=MM,......~78"
echo "NN+,:MM,........~MMN.....................MMM+........MM"
echo "    ,MI........ZMMM.....................MMMZ.......,MM"
echo "    .MM:,,......MN..........ZDZ:........+MZ........7MMMMMM"
echo "  +MMMMM,..................MIIIM+..................MM"
echo "  ..  IMZ..................8MDMM................ZIMM,"
echo "       ,MMMM=...................................,MMMMN"
echo "     .IMMMMM...................................~MM,..7MM,"
echo "   .NM?.  ,NMM7..............................ZMM+"
echo "   ...      .,MMMMNI.....................IMMMM,"
echo "           .:NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM,"
echo "         .NMM+ZZZMMZZZMM~~,,,,++??,M8ZZZMMZZ~7MMN,"
echo "       .MMM.ZZ$,MMZZZZZM7~,,,,,,,,MMZZZZZMM.ZZ+.MMN"
echo "      ~MM+MM~.ZMMZZZZZZZMMD:,,,~MM8ZZZZZZZMM+.ZMM+MM"
echo "     ,M8...:MMMMZZMMMMZZZZZ8MMM8ZZZZZMMM8ZZMMMM:...8M~"
echo "    ,MZ......+MZZ8+..~MZZZZZZZZZZZZZM~..M8ZZM7......MM"
echo "    +M.......MMZZZM~,M8ZZZZZZZZZZZZZMM.~MZZZMM......?M"
echo "    ,M~.....ZMZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ8M......MM"
echo "    .NM~....MMZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZMI....+MM"
echo "      8MMMMMMMZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZMMMMMMM,"
echo "        ...:M8ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ8M+,,"
echo "           .M8ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ8M:M8"
echo "           ,M8ZZZZZZZZZZZZZZZMZZZZZZZZZZZZZZZZM,MN"
echo "           .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:M7"
echo "           ,MI..............7M...............+M:N,"
echo "           .MD..............7M...............ZM.+"
echo "            MM..............?M,.............,MZ."
echo "            ,MM.............MM7.............MM.,"
echo "             .NMMMMD?7IIZNMMM7MMMNZII7ZZMMMM7.+"
echo "                ..IZMNMMZ7,.....+7NMMMMZ+..MM8,"
echo "                                      ..?MMMN+"
echo "                                      .:NMMM8"
echo "                                     ..IMMMM+"
echo "                                    ..ZMMMM~"
echo "                                    .,NMMMD."
echo " Credit to Brandon Adamson "